site_name: IM Docs
site_url: https://isteps-sps-lab.github.io/bf-im
repo_url: https://github.com/isteps-sps-lab/bf-im
site_description: Intervention Manager Documentation
docs_dir: docs
site_dir: html
edit_uri: edit/main/docs/
markdown_extensions:
  - toc
  - fenced_code
  # - codehilite
  - admonition
  - def_list
use_directory_urls: false
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
pages:
  - Home: 'index.md'
  - 'Getting Started' : 'getting-started.md'
  - 'User & Programmers Manual':
    - 'Architecture' : 'architecture.md'
    - 'API' : 'api.md'
    - 'User Manual': 'usermanual.md'
  - 'Installation & Administration Manual':
    - 'Installation Guide': 'installationguide.md'
